### ISSUE TITLE
Importar dados das candidatas no processo seletivo front

### ISSUE THREAD

**Issue by Gustavo1x** [aceleradora-TW/acelera-mais-api#33]
Como mentora operacional
Quer importar dados das candidatas
Para iniciar avaliação dos desafios

# Criterios Front

```
Padrão GWT
  - Given
  - When
  - Then
```
 
## Visualizar o usuário do sistema que importará planilha
DADO que preciso importar os dados dos candidatos no processo seletivo
QUANDO visualizo a interface de importação
ENTÃO vejo as instruções de como a planilha deve ser compartilhada para que possa ser importada

## Importação com sucesso da planilha
DADO que preciso importar os dados dos candidatos no processo seletivo
E que a planilha é um Google Spreadsheet
E que compartilhei o e-mail do sistema com a planilha do usuário de sistema que fará a importação
QUANDO informo a URL da planilha
ENTÃO integro a planilha ao sistema, importando os dados desejados.

## Validação que importação foi feita com sucesso
DADO que solicitação de importação foi realizada
QUANDO importação é finalizada
ENTÃO visualizo mensagem informando quantas candidatas conseguiram ser importadas

## Importação com problema
DADO que solicitação de importação foi realizada
QUANDO importação é finalizada com erros
ENTÃO visualizo mensagem informando os problemas identificados
E problema pode ser
   - Não foi possível conectar com a planilha
   - Dados inválidos
   - ...

# Sketch
![image](https://user-images.githubusercontent.com/79364568/140388319-8fae2cfd-ab23-4b08-9444-8e98e0f7130e.png)

# Tasks 
## FrontEnd

- [x] Campo para receber URL da planilha do GoogleSpreadSheet
- [x] Botão para enviar a URL 
- [x] Post - para enviar dados ao backend
- [x] Notificação de sucesso/erro

Obs:. O card está feito pela na metade, o nome da branch é: 33/importar-dados-das-candidatas-no-processo-seletivo

**Comment by LuizHenrique000** [comment]
Pendências: Aviso de compartilhamento na modal, Verificar que dados não são duplicados
